### ISSUE TITLE
Collaborator request

### ISSUE THREAD

**Issue by WenboSheng** [hushidong/biblatex-zh-cn#1]
Hi. 很高兴看到你开了这个project。其实我几年前也研究过一阵子biblatex，文档也翻译了一部分，但是一个人业余时间做确实很难。

我之前翻译的还是 2.x 版本的，一直到 section 4 的一部分，希望能加到collaborator里面一起做。

**Comment by hushidong** [comment]
hi，当然欢迎，咱们一起做吧。你之前做2.x版的内容不知道差别大不大，不大话可以比较合并一下。
